name: Deploy Serverless Functionality

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: lambci/lambda:build-python3.7
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/serverless-deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # SLS_DEBUG: "*"
      with:
        args: deploy-all-lambdas.sh
