name: Deploy Serverless Functionality

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://nikolaik/python-nodejs:python3.7-nodejs12-alpine
      with:
        node-version: '11.x'
    - run: |
        su
        npm i -g serverless@1.59.3
        cd lambdas
        for directory in $(ls -1)
        do
        pushd $directory
        npm install
        serverless deploy
        popd
        done
      shell: sh
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

