name: Deploy Serverless Functionality

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: dschep/serverless-python-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # SLS_DEBUG: "*"
      with:
        entrypoint: bash
        args: deploy-all-lambdas.sh
